### PR TITLE
[env] Sirius + build environment

### PR DESCRIPTION
**Pull request by toxa81**

### CODE REVIEW

**Comment by bcumming** [comment]
cscs-ci run arbor

**Comment by bcumming** [comment]
cscs-ci run sirius

**Comment by bcumming** [comment]
cscs-ci run sirius

**Comment by bcumming** [comment]
cscs-ci run sirius

**Comment by toxa81** [comment]
cscs-ci run sirius

**Review by bcumming — APPROVED** [review]
lgtm!
It needs some ReFrame tests at some point.

**Pull request merged**
