### PR TITLE
[WIP] Add prgenv-dft example.

### PR DESCRIPTION
**Pull request by toxa81**

### CODE REVIEW

**Comment by bcumming** [comment]
cscs-ci run prgenv-dft

**Comment by bcumming** [comment]
cscs-ci run prgenv-dft

**Comment by toxa81** [comment]
cscs-ci run prgenv-dft

**Comment by bcumming** [comment]
cscs-ci run prgenv-dft

**Comment by toxa81** [comment]
cscs-ci run prgenv-dft

**Comment by toxa81** [comment]
cscs-ci run prgenv-dft

**Comment by toxa81** [comment]
cscs-ci run prgenv-dft

**Comment by toxa81** [comment]
cscs-ci run prgenv-dft

**Comment by toxa81** [comment]
cscs-ci run prgenv-dft

**Comment by toxa81** [comment]
cscs-ci run prgenv-dft

**Comment by toxa81** [comment]
cscs-ci run prgenv-dft

**Comment by toxa81** [comment]
cscs-ci run prgenv-dft

**Comment by toxa81** [comment]
cscs-ci run prgenv-dft

**Comment by toxa81** [comment]
cscs-ci run prgenv-dft

**Comment by toxa81** [comment]
cscs-ci run prgenv-dft

**Comment by toxa81** [comment]
cscs-ci run prgenv-dft

**Comment by toxa81** [comment]
cscs-ci run prgenv-dft

**Comment by toxa81** [comment]
cscs-ci run prgenv-dft

**Comment by toxa81** [comment]
cscs-ci run prgenv-dft

**Comment by toxa81** [comment]
cscs-ci run prgenv-dft

**Comment by toxa81** [comment]
I have large problems with QE at the moment. I can't make 7.1 and 7.2 version run with any of nvhpc 22.5 23.1 23.3 23.5
On bare metal Hohgant only qe-7.1 with nvhpc-22.5 (native from CPE) works.

**Comment by bcumming** [comment]
> 

This is an issue - ideally NVHPC SDK would not install any version of CUDA, and we can use the version that has already been installed.

Your proposed variant for the `nvhpc` package is a good one, but I don't know if it addresses the issue: the correct version of CUDA will be installed inside the SDK, however we don't want to actually use that copy because it isn't the `cuda@11.8` that we install separately inside the environment.

There is a runtime variable `NVHPC_CUDA_HOME` that will direct `nvhpcsdk` to use a different installation of CUDA. If we could point that to the same value as `CUDA_HOME` set by our `cuda@11.8` installation, the issue would be solved.

**Comment by bcumming** [comment]
cscs-ci run prgenv-dft

**Comment by toxa81** [comment]
Still bad
```
ldd /user-environment/env/default/bin/pw.x | grep cuda | grep 12
	libcudart.so.12 => /user-environment/linux-sles15-zen2/gcc-11.3.0/nvhpc-23.1-wobywnthlcaenfo3f7uxnk3kmayjixar/Linux_x86_64/23.1/cuda/12.0/lib64/libcudart.so.12 (0x00007f29f9668000)
	```

**Comment by toxa81** [comment]
@bcumming finally! this thing works! The performance is the same as on bare metal. Last point: I want to rename the folder to `quantumespresso` to reflect the reality.

**Comment by toxa81** [comment]
renamed to `quantumespresso`

**Pull request closed without merging**
