### PR TITLE
ddt/23

### PR DESCRIPTION
**Pull request by jgphpc**
- https://jira.cscs.ch/browse/VCUE-74
- https://jira.cscs.ch/browse/VCUE-72

### CODE REVIEW

**Review by bcumming — CHANGES_REQUESTED** [review]
Thanks @jgphpc!

I will configure the CI/CD.

Before we deploy, we should configure a `/tools` path on Balfrin and other vClusters, and the SLURM plugin that allows us to mount multiple images.

**Comment by bcumming** [comment]
cscs-ci run ddt

**Comment by jgphpc** [comment]
cscs-ci run ddt

**Comment by bcumming** [comment]
cscs-ci run ddt

**Comment by jgphpc** [comment]
https://github.com/eth-cscs/alps-spack-stacks/pull/43

**Comment by bcumming** [comment]
Please iinclude the docs from #43 in this PR? That way the documentation is aligned with the state of the repo, and the docs and implementation can be reviewed together.

**Pull request closed without merging**
