### PR TITLE
add pe-dft pipeline

### PR DESCRIPTION
**Pull request by finkandreas**
- Adding sstool as submodule
- Adding ci/pe-dft.yml describing how to build the spack squashfs store

### CODE REVIEW

**Comment by finkandreas** [comment]
cscs-ci run pe-dft

**Comment by finkandreas** [comment]
cscs-ci run pe-dftcscs-ci run pe-dft

**Comment by finkandreas** [comment]
cscs-ci run pe-dft

**Comment by finkandreas** [comment]
cscs-ci run pe-dft

**Comment by finkandreas** [comment]
cscs-ci run pe-dft

**Comment by finkandreas** [comment]
cscs-ci run pe-dft

**Comment by finkandreas** [comment]
cscs-ci run pe-dft

**Comment by toxa81** [comment]
Very nice!

**Comment by finkandreas** [comment]
cscs-ci run pe-dft

**Pull request closed without merging**
